package CComponents;


public enum MessageBlobType{
	/*
	 * 枚举类型
	 * */
	CHAT_TEXT,CHAT_PICTURE,LOGOUT//这三者只发送,无需服务器答复.
	
	,ADD_CONTACT_QUEST,ADD_CONTACT_ANSWER//添加好友请求和答复
	,ONLINE_STATE_QUEST,ONLINE_STATE_ANSWER//询问在线状态及答复
	,LOGIN_QUEST,LOGIN_ANSWER//登录请求和答复

	,EDIT_MY_PROFILE_QUEST,EDIT_MY_PROFILE_ANSWER//编辑个人资料请求和答复
	,EDIT_FRIEND_PROFILE_QUEST,EDIT_FRIEND_PROFILE_ANSWER//编辑好友备注请求及答复
	,EDITT_MY_KEY_QUEST,EDIT_MY_KEY_ANSWER//更改密码请求及答复
	,DELETE_CONTACT_QUEST,DELETE_CONTACT_ANSWER//删除好友请求及答复
	,REGISTER_QUEST,REGISTER_ANSWER//注册请求及答复
	,FIND_FRIEND_QUEST,FIND_FRIEEND_ANSWER//查找好友请求及答复
	,SELF_PROFILE_QUEST,FRIEND_PROFILE_QUEST//个人资料及好友资料的请求
	,SELF_PROFILE_ANSWER,FRIEND_PROFILE_ANSWER;//个人资料及好友资料的答复

}
